
title: Dan Hachuel 
logo: "/Index.html/Foto_Github.png?raw=true"

description: Bookmark this to keep an eye on my project updates!
 First description 
  <br><br>
  
  Second description 
  <br><br>
  
  <a href="https://www.linkedin.com/in/dan-hachuel/">View My LinkedIn Profile</a> 
  
  <br><br>
  
theme: jekyll-theme-minimal 
google_analytics: G-FRHQQBBLJR
